---
title: "番組嗜好度の推定"
author: "Yutaka Kuroki"
date: "2018/10/26"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    theme: cosmo
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
md_extensions: -ascii_identifiers
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      cache = TRUE)
```

```{r import, cache=FALSE}
library(tidyverse)
library(lubridate)
library(dbplyr)
library(dbplot)
library(RPostgreSQL)
library(ggforce)
library(DT)

theme_set(theme_bw(base_family = "HiraKakuPro-W3"))
```

```{r connect, cache=FALSE}
conn <- dbConnect(PostgreSQL(),
                  host = scan("connection.txt", what = character())[1],
                  port = scan("connection.txt", what = character())[2], 
                  dbname = scan("connection.txt", what = character())[3], 
                  user = scan("connection.txt", what = character())[4], 
                  password = scan("connection.txt", what = character())[5])

# ログ
orgn <- conn %>% 
  tbl(from = dbplyr::in_schema("edit", "tv_orgn_program_2")) 
tmp <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_orgn_p_cv")) 
play <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_play_p_cv"))
web <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "t_weblog"))
# CM
jiten <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "jiten_data"))
brand <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "m_cm_tv_brand"))
adv <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "m_cm_tv_advertiser"))
# その他マスタ
program <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_program")) 
ban <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "bancluster_mst")) 
ban1 <- conn %>% 
  tbl(from = dbplyr::in_schema("sub_mst", "ban_code1_mst")) 
sta <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "sta_mst"))
sample <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_sample_p_cv"))
job <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "job_mst"))
# アンケート
prof_data <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "profiledata"))
prof_mst <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "profilemaster"))
prof <- prof_data %>% 
  left_join(prof_mst, by = c("qu_genre_code", "question_code", "answer_code"))
```

# 番組距離行列

```{r join_ban_ban1}
data <- ban %>% 
  left_join(ban1, by = "ban_code1") %>% 
  arrange(ban_code1, ban_code2, ban_code3) %>% 
  collect() %>% 
  mutate(ban_name = str_remove_all(ban_name, pattern = " "),
         ban_code1_naiyou = str_remove_all(ban_code1_naiyou, pattern = " "),
         ban_id = 1:n()) %>% 
  as.data.frame()
```

```{r}
ban_dist <- matrix(nrow = nrow(data), ncol = nrow(data))
  colnames(ban_dist) <- 1:nrow(data)
  rownames(ban_dist) <- 1:nrow(data)
for(i in 1:nrow(data)){
  ban_dist[i,i] <- 0
  for(j in 1:nrow(data)){
    if (data$ban_code1[i] == data$ban_code1[j] &
        data$ban_code2[i] == data$ban_code2[j] &
        data$ban_code3[i] == data$ban_code3[j]) {
      ban_dist[i,j] <- ban_dist[j,i] <- 0
    } else if (data$ban_code1[i] == data$ban_code1[j] &
        data$ban_code2[i] == data$ban_code2[j] &
        data$ban_code3[i] != data$ban_code3[j]) {
      ban_dist[i,j] <- ban_dist[j,i] <- 1
    } else if (data$ban_code1[i] == data$ban_code1[j] &
        data$ban_code2[i] != data$ban_code2[j] &
        data$ban_code3[i] != data$ban_code3[j]) {
      ban_dist[i,j] <- ban_dist[j,i] <- 2
    } 
  }
}
ban_dist[which(is.na(ban_dist))] <- 3
mds <- MASS::isoMDS(ban_dist)
mds_df <- as.data.frame(mds$points) %>% 
  mutate(name = data$ban_name)
mds_df %>% 
  ggplot(aes(V1, V2))+
  geom_text(aes(label = name), family = "HiraKakuPro-W3", size=1)
```

```{r}
tmp <- orgn %>% 
  select(house_num, watch_time, program_code, program_start_time, station_code) %>% 
  left_join(program, by = c("program_code", "program_start_time")) %>% 
  select(house_num, program_time, watch_time, program_code, ban_code1:ban_code3) %>% 
  mutate(watch_rate = watch_time / program_time) %>% 
  group_by(house_num, ban_code1) %>% 
  summarise(sum_rate = sum(watch_rate)) %>% 
  ungroup %>% 
  collect()

ban1 <- collect(ban1) %>% 
  mutate(ban_code1_naiyou = str_remove_all(ban_code1_naiyou, pattern = " "))

watch_mat <- tmp  %>% 
  left_join(ban1, by = c("ban_code1")) %>% 
  select(house_num, ban_code1_naiyou, sum_rate) %>% 
  spread(ban_code1_naiyou, sum_rate, fill = 0) %>% 
  gather(ban_name, sum_rate, -house_num) %>% 
  group_by(house_num) %>% 
  mutate(sum_rate = scale(sum_rate)) %>% 
  filter(!is.nan(sum_rate)) %>% 
  spread(ban_name, sum_rate, fill=-0.5) %>% 
  as.data.frame() %>% 
  column_to_rownames("house_num")
  
pca <- watch_mat %>% 
  prcomp()

ban_map <- t(t(pca$rotation)*pca$sdev) %>% 
  as.data.frame() %>% 
  rownames_to_column("ban_clust") %>% 
  arrange(desc(abs(PC1)), desc(abs(PC2))) %>% 
  head(20)

inno <- prof %>% 
  filter(qu_genre_code == 25, question_code == 4) %>% 
  select(house_num, answer_code) %>% 
  collect()

p <- pca$x %>% 
  as.data.frame() %>% 
  mutate(house_num = as.integer(rownames(watch_mat))) %>% 
  left_join(inno, by = "house_num") %>% 
  ggplot(aes(PC1, PC2))+
  geom_density_2d()+
  geom_label_repel(data = ban_map, aes(PC1*3, PC2*3, label = ban_clust), colour = "blue", family = "HiraKakuPro-W3")+
  facet_wrap(~answer_code)


  
  
```

