---
title: "MARS"
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    toc_float: true
    toc_depth: 2
    fig_width: 7
    theme: cosmo
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
md_extensions: -ascii_identifiers
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      cache = TRUE)
```

```{r import, cache=FALSE}
library(tidyverse)
library(lubridate)
library(dbplyr)
library(dbplot)
library(RPostgreSQL)
library(ggforce)
library(DT)
library(NMF)
library(knitr)
library(minerva)
library(GGally)
library(ggalluvial)

theme_set(theme_bw(base_family = "HiraKakuPro-W3"))
```

```{r connect, cache=FALSE}
conn <- dbConnect(PostgreSQL(),
                  host = scan("connection.txt", what = character())[1],
                  port = scan("connection.txt", what = character())[2], 
                  dbname = scan("connection.txt", what = character())[3], 
                  user = scan("connection.txt", what = character())[4], 
                  password = scan("connection.txt", what = character())[5])

orgn2 <- conn %>% 
  tbl(from = dbplyr::in_schema("edit", "tv_orgn_program_2")) 
orgn1 <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_orgn_p_cv")) 
play <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_play_p_cv"))
web <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "t_weblog"))
## CM
jiten <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "jiten_data"))
brand <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "m_cm_tv_brand"))
adv <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "m_cm_tv_advertiser"))
## その他マスタ
program <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_program")) 
ban <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "bancluster_mst")) 
ban1 <- conn %>% 
  tbl(from = dbplyr::in_schema("sub_mst", "ban_code1_mst")) 
sta <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "sta_mst"))
sample <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "tv_sample_p_cv"))
job <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "job_mst"))
## アンケート
prof_data <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "profiledata"))
prof_mst <- conn %>% 
  tbl(from = dbplyr::in_schema("processed", "profilemaster"))
prof <- prof_data %>% 
  left_join(prof_mst, by = c("qu_genre_code", "question_code", "answer_code"))
```

# はじめに

Cyber Agentの論文「インターネットテレビサービスAbemaTVにおけるユーザーアクティビティ分析」を追試したい

## 論文要約

MARS(multivariate adaptive regression splines)を用いてAbemaTVユーザの継続・離脱分析を行い，離脱につながるような行動を示唆した．

**課題**  
インターネット上のサービスは据え置き型のテレビと比べて，ユーザーにとっては初期費用がかからないなどの理由により導入が簡単な反面，サービス利用継続率が時間とともに低下していきやすいという問題点を抱えている．  
ドラマとかに絞れば今回のデータにも使えそう

**目的変数**  
週間アクティブ日数$y$


```{r}
dau <- orgn1 %>% 
  distinct(house_num, br_date) %>% 
  collect()
  
dau %>% 
  count(br_date) %>% 
  ggplot(aes(br_date, n))+
  geom_line()+
  labs(title = "DAU")

dau %>% 
  mutate(year = year(br_date),
         week = week(br_date)) %>% 
  distinct(year, week, house_num) %>% 
  count(year, week) %>% 
  mutate(index = 1:n()) %>% 
  ggplot(aes(index, n))+
  geom_line()+
  labs(title = "WAU")
```


```{r}
wau <- dau %>% 
  mutate(year = year(br_date),
         week = week(br_date)) %>% 
  count(year, week, house_num) %>% 
  spread(house_num, n, fill=0) %>% 
  gather(house_num, n, -year, -week)
wau %>% 
  ggplot(aes(n))+
  geom_bar()
```

